export const BASE64_PREFIX = 'data:image/jpeg;base64,';
export const SLIDE_SHOW_MODE = 'slideShow';
export const PREDICTION_MODE = 'prediction';

export const KNOWN_CLASSES = [
  'AM Hummer',
  'Acura Integra Type R',
  'Acura RL 2nd gen',
  'Acura TL 4th gen',
  'Acura TL 3rd gen',
  'Acura TSX',
  'Acura ZDX',
  'Aston Martin V8 Vantage',
  'Aston Martin Virage',
  'Audi 100',
  'Audi A4 7th gen',
  'Audi A5 1st gen',
  'Audi R8',
  'Audi A4 8th gen',
  'Audi A6 6th gen',
  'Audi TT 2nd gen',
  'Audi V8',
  'BMW 1 Series 1st gen',
  'BMW 3 Series 5th gen',
  'BMW 3 Series 6th gen',
  'BMW 5 Series 6th gen',
  'BMW 6 Series 1st gen',
  'BMW M3 5th gen',
  'BMW M5 5th gen',
  'BMW X3 1st gen',
  'BMW X5 2nd gen',
  'BMW X6 1st gen',
  'BMW Z4 3rd gen',
  'Bentley Arnage',
  'Bentley Continental 1st gen',
  'Bentley Continental 2nd gen',
  'Bentley Continental Flying Spur',
  'Bentley Mulsanne',
  'Bugatti Veyron',
  'Buick Enclave',
  'Buick Rainier',
  'Buick Regal 5th gen',
  'Buick Verano 1st gen',
  'Cadillac CTS-V',
  'Cadillac Escalade EXT',
  'Cadillac SRX 2nd gen',
  'Chevrolet Avalanche 2nd gen',
  'Chevrolet Camaro 5th gen',
  'Chevrolet Cobalt SS',
  'Chevrolet Corvette C6',
  'Chevrolet Express',
  'Chevrolet Express Appearance Package',
  'Chevrolet HHR SS'
];
