export const BASE64_PREFIX = 'data:image/jpeg;base64,';
export const SLIDE_SHOW_MODE = 'slideShow';
export const PREDICTION_MODE = 'prediction';

export const KNOWN_CLASSES = [
  'AM Hummer',
  'Acura Integra Type R',
  'Acura RL',
  'Acura TL',
  'Acura TL Type-S',
  'Acura TSX',
  'Acura ZDX',
  'Aston Martin V8 Vantage',
  'Aston Martin Virage',
  'Audi 100',
  'Audi A4',
  'Audi A5',
  'Audi R8',
  'Audi S4',
  'Audi S6',
  'Audi TT',
  'Audi V8',
  'BMW 1 Series',
  'BMW 3 Series 5th gen',
  'BMW 3 Series 6th gen',
  'BMW 5 Series',
  'BMW 6 Series',
  'BMW M3',
  'BMW M5',
  'BMW X3',
  'BMW X5',
  'BMW X6',
  'BMW Z4',
  'Bentley Arnage',
  'Bentley Continental 1st gen',
  'Bentley Continental 2nd gen',
  'Bentley Continental Flying Spur',
  'Bentley Mulsanne',
  'Bugatti Veyron',
  'Buick Enclave',
  'Buick Rainier',
  'Buick Regal GS',
  'Buick Verano',
  'Cadillac CTS-V',
  'Cadillac Escalade EXT',
  'Cadillac SRX',
  'Chevrolet Avalanche',
  'Chevrolet Camaro',
  'Chevrolet Cobalt SS',
  'Chevrolet Corvette',
  'Chevrolet Express',
  'Chevrolet Express Appearance Package',
  'Chevrolet HHR SS',
];
